//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arya.Framework.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arya.Framework.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute does not exists..
        /// </summary>
        public static string AttributeDoesNotExistWarningMessage {
            get {
                return ResourceManager.GetString("AttributeDoesNotExistWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute name and  type does  not match with database..
        /// </summary>
        public static string AttributeNameSameTypeDifferentWarningMessage {
            get {
                return ResourceManager.GetString("AttributeNameSameTypeDifferentWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lov in the file.
        /// </summary>
        public static string CreateLovFlagOffWarningLineDataText {
            get {
                return ResourceManager.GetString("CreateLovFlagOffWarningLineDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Missing LovFlag  set to false. No New Lov was created.
        /// </summary>
        public static string CreateLovFlagOffWarningMessage {
            get {
                return ResourceManager.GetString("CreateLovFlagOffWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All new attributes in file..
        /// </summary>
        public static string CreateMissingAttributesFlagOffWarningLineDataText {
            get {
                return ResourceManager.GetString("CreateMissingAttributesFlagOffWarningLineDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Missing Attributes Flag set to false. No New Attribute created..
        /// </summary>
        public static string CreateMissingAttributesFlagOffWarningMessage {
            get {
                return ResourceManager.GetString("CreateMissingAttributesFlagOffWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Missing Sku Flag set to false. No New Sku created.
        /// </summary>
        public static string CreateMissingSkuFlagOffWarningMessage {
            get {
                return ResourceManager.GetString("CreateMissingSkuFlagOffWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All new taxonomy in file.
        /// </summary>
        public static string CreateMissingTaxonomiesFlagOffLineDataText {
            get {
                return ResourceManager.GetString("CreateMissingTaxonomiesFlagOffLineDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MissingTaxonomy Flag  set to false. No New Taxonomy created.
        /// </summary>
        public static string CreateMissingTaxonomiesFlagOffWarningMessage {
            get {
                return ResourceManager.GetString("CreateMissingTaxonomiesFlagOffWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All new values.
        /// </summary>
        public static string CreateMissingValuesFlagOffLineDataText {
            get {
                return ResourceManager.GetString("CreateMissingValuesFlagOffLineDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create missing value flag set to false.
        /// </summary>
        public static string CreateMissingValuesFlagOffWanringMessage {
            get {
                return ResourceManager.GetString("CreateMissingValuesFlagOffWanringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new taxonomy failed.
        /// </summary>
        public static string CreateNewTaxonomyFailWorningMessage {
            get {
                return ResourceManager.GetString("CreateNewTaxonomyFailWorningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order does not have a valid number.
        /// </summary>
        public static string DisplayOrderNotValidNumberWarningMessage {
            get {
                return ResourceManager.GetString("DisplayOrderNotValidNumberWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attribute on single taxonomy node..
        /// </summary>
        public static string DuplicateAttributeSingleTaxonomyWarningMessage {
            get {
                return ResourceManager.GetString("DuplicateAttributeSingleTaxonomyWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate entity id.
        /// </summary>
        public static string DuplicateEntityIdWarningMessage {
            get {
                return ResourceManager.GetString("DuplicateEntityIdWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file does not exits or the file path is not valid.
        /// </summary>
        public static string EnrichmentImageFileNotPresentWarningMessage {
            get {
                return ResourceManager.GetString("EnrichmentImageFileNotPresentWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityInfoID does not Exists in Db.
        /// </summary>
        public static string EntityInfoIDDoesNotExistWarningMessage {
            get {
                return ResourceManager.GetString("EntityInfoIDDoesNotExistWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string ExportAssetDirectoryName {
            get {
                return ResourceManager.GetString("ExportAssetDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Records:.
        /// </summary>
        public static string IgnoredRecordCountIdentifierText {
            get {
                return ResourceManager.GetString("IgnoredRecordCountIdentifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute type not defined in the database..
        /// </summary>
        public static string InvalidAttributeTypeWarningMessage {
            get {
                return ResourceManager.GetString("InvalidAttributeTypeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row is missing data columns.
        /// </summary>
        public static string InvalidRowInInputFileMessage {
            get {
                return ResourceManager.GetString("InvalidRowInInputFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item does not Exists in Db.
        /// </summary>
        public static string ItemDoesNotExistWarningMessage {
            get {
                return ResourceManager.GetString("ItemDoesNotExistWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id is present in multiple taxonomies .
        /// </summary>
        public static string ItemIdContainsMultipleTaxonomiesWanringMessage {
            get {
                return ResourceManager.GetString("ItemIdContainsMultipleTaxonomiesWanringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta-attribute not found.
        /// </summary>
        public static string MetaAttributeNotFoundWarningMessage {
            get {
                return ResourceManager.GetString("MetaAttributeNotFoundWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Records:.
        /// </summary>
        public static string NewRecordCountIdentifierText {
            get {
                return ResourceManager.GetString("NewRecordCountIdentifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required value column has null values..
        /// </summary>
        public static string RequiredValueNullWarningMessage {
            get {
                return ResourceManager.GetString("RequiredValueNullWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar attribute info in database..
        /// </summary>
        public static string SimilarAttributeWarningMessage {
            get {
                return ResourceManager.GetString("SimilarAttributeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add sku to a cross listed node.
        /// </summary>
        public static string SkuOnCrossListedTaxonomyDoesNotExistsWarningMessage {
            get {
                return ResourceManager.GetString("SkuOnCrossListedTaxonomyDoesNotExistsWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy does not exists.
        /// </summary>
        public static string TaxonomyDoesNotExistsWarningMessage {
            get {
                return ResourceManager.GetString("TaxonomyDoesNotExistsWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy or Attribute name is missing.
        /// </summary>
        public static string TaxonomyOrAttributeMissingWarningMessage {
            get {
                return ResourceManager.GetString("TaxonomyOrAttributeMissingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Records:.
        /// </summary>
        public static string UpdatedRecordCountIdentifierText {
            get {
                return ResourceManager.GetString("UpdatedRecordCountIdentifierText", resourceCulture);
            }
        }
    }
}
