#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arya.Framework.Data.Services
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AryaServicesAlpha")]
	public partial class AryaServicesDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAryaSchedule(AryaSchedule instance);
    partial void UpdateAryaSchedule(AryaSchedule instance);
    partial void DeleteAryaSchedule(AryaSchedule instance);
    partial void InsertAryaTask(AryaTask instance);
    partial void UpdateAryaTask(AryaTask instance);
    partial void DeleteAryaTask(AryaTask instance);
    #endregion
		
		public AryaServicesDbDataContext() : 
				base(global::Arya.Framework.Properties.Settings.Default.AryaServicesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AryaServicesDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AryaServicesDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AryaServicesDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AryaServicesDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AryaSchedule> AryaSchedules
		{
			get
			{
				return this.GetTable<AryaSchedule>();
			}
		}
		
		public System.Data.Linq.Table<AryaTask> AryaTasks
		{
			get
			{
				return this.GetTable<AryaTask>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AryaSchedule")]
	public partial class AryaSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _ProjectID;
		
		private string _Description;
		
		private string _ArgumentDirectoryPath;
		
		private System.Guid _SubmittedBy;
		
		private System.DateTime _SubmittedOn;
		
		private int _Interval;
		
		private System.DateTime _NextExecution;
		
		private System.Nullable<System.DateTime> _LastExecution;
		
		private string _EmailTo;
		
		private string _JobType;
		
		private EntitySet<AryaTask> _AryaTasks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnProjectIDChanging(System.Guid value);
    partial void OnProjectIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnArgumentDirectoryPathChanging(string value);
    partial void OnArgumentDirectoryPathChanged();
    partial void OnSubmittedByChanging(System.Guid value);
    partial void OnSubmittedByChanged();
    partial void OnSubmittedOnChanging(System.DateTime value);
    partial void OnSubmittedOnChanged();
    partial void OnIntervalChanging(int value);
    partial void OnIntervalChanged();
    partial void OnNextExecutionChanging(System.DateTime value);
    partial void OnNextExecutionChanged();
    partial void OnLastExecutionChanging(System.Nullable<System.DateTime> value);
    partial void OnLastExecutionChanged();
    partial void OnEmailToChanging(string value);
    partial void OnEmailToChanged();
    partial void OnJobTypeChanging(string value);
    partial void OnJobTypeChanged();
    #endregion
		
		public AryaSchedule()
		{
			this._AryaTasks = new EntitySet<AryaTask>(new Action<AryaTask>(this.attach_AryaTasks), new Action<AryaTask>(this.detach_AryaTasks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this.OnProjectIDChanging(value);
					this.SendPropertyChanging();
					this._ProjectID = value;
					this.SendPropertyChanged("ProjectID");
					this.OnProjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArgumentDirectoryPath", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string ArgumentDirectoryPath
		{
			get
			{
				return this._ArgumentDirectoryPath;
			}
			set
			{
				if ((this._ArgumentDirectoryPath != value))
				{
					this.OnArgumentDirectoryPathChanging(value);
					this.SendPropertyChanging();
					this._ArgumentDirectoryPath = value;
					this.SendPropertyChanged("ArgumentDirectoryPath");
					this.OnArgumentDirectoryPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedBy", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SubmittedBy
		{
			get
			{
				return this._SubmittedBy;
			}
			set
			{
				if ((this._SubmittedBy != value))
				{
					this.OnSubmittedByChanging(value);
					this.SendPropertyChanging();
					this._SubmittedBy = value;
					this.SendPropertyChanged("SubmittedBy");
					this.OnSubmittedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedOn", DbType="DateTime NOT NULL")]
		public System.DateTime SubmittedOn
		{
			get
			{
				return this._SubmittedOn;
			}
			set
			{
				if ((this._SubmittedOn != value))
				{
					this.OnSubmittedOnChanging(value);
					this.SendPropertyChanging();
					this._SubmittedOn = value;
					this.SendPropertyChanged("SubmittedOn");
					this.OnSubmittedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interval", DbType="Int NOT NULL")]
		public int Interval
		{
			get
			{
				return this._Interval;
			}
			set
			{
				if ((this._Interval != value))
				{
					this.OnIntervalChanging(value);
					this.SendPropertyChanging();
					this._Interval = value;
					this.SendPropertyChanged("Interval");
					this.OnIntervalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextExecution", DbType="DateTime NOT NULL")]
		public System.DateTime NextExecution
		{
			get
			{
				return this._NextExecution;
			}
			set
			{
				if ((this._NextExecution != value))
				{
					this.OnNextExecutionChanging(value);
					this.SendPropertyChanging();
					this._NextExecution = value;
					this.SendPropertyChanged("NextExecution");
					this.OnNextExecutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastExecution", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastExecution
		{
			get
			{
				return this._LastExecution;
			}
			set
			{
				if ((this._LastExecution != value))
				{
					this.OnLastExecutionChanging(value);
					this.SendPropertyChanging();
					this._LastExecution = value;
					this.SendPropertyChanged("LastExecution");
					this.OnLastExecutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTo", DbType="VarChar(4000)")]
		public string EmailTo
		{
			get
			{
				return this._EmailTo;
			}
			set
			{
				if ((this._EmailTo != value))
				{
					this.OnEmailToChanging(value);
					this.SendPropertyChanging();
					this._EmailTo = value;
					this.SendPropertyChanged("EmailTo");
					this.OnEmailToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobType", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string JobType
		{
			get
			{
				return this._JobType;
			}
			set
			{
				if ((this._JobType != value))
				{
					this.OnJobTypeChanging(value);
					this.SendPropertyChanging();
					this._JobType = value;
					this.SendPropertyChanged("JobType");
					this.OnJobTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AryaSchedule_AryaTask", Storage="_AryaTasks", ThisKey="ID", OtherKey="ScheduleID")]
		public EntitySet<AryaTask> AryaTasks
		{
			get
			{
				return this._AryaTasks;
			}
			set
			{
				this._AryaTasks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AryaTasks(AryaTask entity)
		{
			this.SendPropertyChanging();
			entity.AryaSchedule = this;
		}
		
		private void detach_AryaTasks(AryaTask entity)
		{
			this.SendPropertyChanging();
			entity.AryaSchedule = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AryaTask")]
	public partial class AryaTask : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<System.Guid> _ScheduleID;
		
		private System.Guid _ProjectID;
		
		private string _Description;
		
		private string _ArgumentDirectoryPath;
		
		private string _Status;
		
		private string _StatusMessage;
		
		private System.Guid _SubmittedBy;
		
		private System.DateTime _SubmittedOn;
		
		private System.DateTime _LastUpdateOn;
		
		private string _JobType;
		
		private System.Nullable<System.DateTime> _JobAssignedOn;
		
		private EntityRef<AryaSchedule> _AryaSchedule;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnScheduleIDChanging(System.Nullable<System.Guid> value);
    partial void OnScheduleIDChanged();
    partial void OnProjectIDChanging(System.Guid value);
    partial void OnProjectIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnArgumentDirectoryPathChanging(string value);
    partial void OnArgumentDirectoryPathChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnStatusMessageChanging(string value);
    partial void OnStatusMessageChanged();
    partial void OnSubmittedByChanging(System.Guid value);
    partial void OnSubmittedByChanged();
    partial void OnSubmittedOnChanging(System.DateTime value);
    partial void OnSubmittedOnChanged();
    partial void OnLastUpdateOnChanging(System.DateTime value);
    partial void OnLastUpdateOnChanged();
    partial void OnJobTypeChanging(string value);
    partial void OnJobTypeChanged();
    partial void OnJobAssignedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnJobAssignedOnChanged();
    #endregion
		
		public AryaTask()
		{
			this._AryaSchedule = default(EntityRef<AryaSchedule>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScheduleID
		{
			get
			{
				return this._ScheduleID;
			}
			set
			{
				if ((this._ScheduleID != value))
				{
					if (this._AryaSchedule.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnScheduleIDChanging(value);
					this.SendPropertyChanging();
					this._ScheduleID = value;
					this.SendPropertyChanged("ScheduleID");
					this.OnScheduleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this.OnProjectIDChanging(value);
					this.SendPropertyChanging();
					this._ProjectID = value;
					this.SendPropertyChanged("ProjectID");
					this.OnProjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArgumentDirectoryPath", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string ArgumentDirectoryPath
		{
			get
			{
				return this._ArgumentDirectoryPath;
			}
			set
			{
				if ((this._ArgumentDirectoryPath != value))
				{
					this.OnArgumentDirectoryPathChanging(value);
					this.SendPropertyChanging();
					this._ArgumentDirectoryPath = value;
					this.SendPropertyChanged("ArgumentDirectoryPath");
					this.OnArgumentDirectoryPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusMessage", DbType="NVarChar(4000)")]
		public string StatusMessage
		{
			get
			{
				return this._StatusMessage;
			}
			set
			{
				if ((this._StatusMessage != value))
				{
					this.OnStatusMessageChanging(value);
					this.SendPropertyChanging();
					this._StatusMessage = value;
					this.SendPropertyChanged("StatusMessage");
					this.OnStatusMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedBy", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SubmittedBy
		{
			get
			{
				return this._SubmittedBy;
			}
			set
			{
				if ((this._SubmittedBy != value))
				{
					this.OnSubmittedByChanging(value);
					this.SendPropertyChanging();
					this._SubmittedBy = value;
					this.SendPropertyChanged("SubmittedBy");
					this.OnSubmittedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedOn", DbType="DateTime NOT NULL")]
		public System.DateTime SubmittedOn
		{
			get
			{
				return this._SubmittedOn;
			}
			set
			{
				if ((this._SubmittedOn != value))
				{
					this.OnSubmittedOnChanging(value);
					this.SendPropertyChanging();
					this._SubmittedOn = value;
					this.SendPropertyChanged("SubmittedOn");
					this.OnSubmittedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateOn", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdateOn
		{
			get
			{
				return this._LastUpdateOn;
			}
			set
			{
				if ((this._LastUpdateOn != value))
				{
					this.OnLastUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateOn = value;
					this.SendPropertyChanged("LastUpdateOn");
					this.OnLastUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobType", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string JobType
		{
			get
			{
				return this._JobType;
			}
			set
			{
				if ((this._JobType != value))
				{
					this.OnJobTypeChanging(value);
					this.SendPropertyChanging();
					this._JobType = value;
					this.SendPropertyChanged("JobType");
					this.OnJobTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobAssignedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> JobAssignedOn
		{
			get
			{
				return this._JobAssignedOn;
			}
			set
			{
				if ((this._JobAssignedOn != value))
				{
					this.OnJobAssignedOnChanging(value);
					this.SendPropertyChanging();
					this._JobAssignedOn = value;
					this.SendPropertyChanged("JobAssignedOn");
					this.OnJobAssignedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AryaSchedule_AryaTask", Storage="_AryaSchedule", ThisKey="ScheduleID", OtherKey="ID", IsForeignKey=true)]
		public AryaSchedule AryaSchedule
		{
			get
			{
				return this._AryaSchedule.Entity;
			}
			set
			{
				AryaSchedule previousValue = this._AryaSchedule.Entity;
				if (((previousValue != value) 
							|| (this._AryaSchedule.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AryaSchedule.Entity = null;
						previousValue.AryaTasks.Remove(this);
					}
					this._AryaSchedule.Entity = value;
					if ((value != null))
					{
						value.AryaTasks.Add(this);
						this._ScheduleID = value.ID;
					}
					else
					{
						this._ScheduleID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("AryaSchedule");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
