//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arya.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arya.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeId.
        /// </summary>
        public static string AttributeIdAttributeName {
            get {
                return ResourceManager.GetString("AttributeIdAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] en_GB {
            get {
                object obj = ResourceManager.GetObject("en_GB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46280
        ///abaft
        ///abbreviation/M
        ///abdicate/DNGSn
        ///Abelard/M
        ///abider/M
        ///Abidjan
        ///ablaze
        ///abloom
        ///aboveground
        ///abrader/M
        ///Abram/M
        ///abreaction/MS
        ///abrogator/MS
        ///abscond/DRSG
        ///absinthe/MS
        ///absoluteness/S
        ///absorbency/SM
        ///abstract/ShTVDPiGY
        ///absurdness/S
        ///Abuja/M
        ///Abyssinia/M
        ///Acadia
        ///accede/SDG
        ///accept/BDSRVGkhl
        ///acceptable/P
        ///accepted/U
        ///accommodate/DGnkSNVu
        ///accommodating/U
        ///accompanier/M
        ///accomplish/RLSGD
        ///accordion/MS3
        ///accost/DSG
        ///accountant/SM
        ///accrual/MS
        ///accurately/I
        ///accusal/M
        ///achene/SM
        ///achievable/U
        ///achi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_GB1 {
            get {
                return ResourceManager.GetString("en_GB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] en_US {
            get {
                object obj = ResourceManager.GetObject("en_US", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62118
        ///0/nm
        ///1/n1
        ///2/nm
        ///3/nm
        ///4/nm
        ///5/nm
        ///6/nm
        ///7/nm
        ///8/nm
        ///9/nm
        ///0th/pt
        ///1st/p
        ///1th/tc
        ///2nd/p
        ///2th/tc
        ///3rd/p
        ///3th/tc
        ///4th/pt
        ///5th/pt
        ///6th/pt
        ///7th/pt
        ///8th/pt
        ///9th/pt
        ///a
        ///A
        ///AA
        ///AAA
        ///Aachen/M
        ///aardvark/SM
        ///Aaren/M
        ///Aarhus/M
        ///Aarika/M
        ///Aaron/M
        ///AB
        ///aback
        ///abacus/SM
        ///abaft
        ///Abagael/M
        ///Abagail/M
        ///abalone/SM
        ///abandoner/M
        ///abandon/LGDRS
        ///abandonment/SM
        ///abase/LGDSR
        ///abasement/S
        ///abaser/M
        ///abashed/UY
        ///abashment/MS
        ///abash/SDLG
        ///abate/DSRLG
        ///abated/U
        ///abatement/MS
        ///abater/M
        ///abattoir/SM
        ///Abba/M
        ///Abbe/M
        ///abbé/S
        ///abb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US1 {
            get {
                return ResourceManager.GetString("en_US1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://dev.empirisense.com.
        /// </summary>
        public static string FtpUri {
            get {
                return ResourceManager.GetString("FtpUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dev.empirisense.com/AryaAssets/.
        /// </summary>
        public static string HttpBaseUri {
            get {
                return ResourceManager.GetString("HttpBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image FileNameNoExtension.
        /// </summary>
        public static string ImageSkuGuidFileNameNoExtensionAttributeName {
            get {
                return ResourceManager.GetString("ImageSkuGuidFileNameNoExtensionAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image FileExtension.
        /// </summary>
        public static string ImageSkuImageFileExtensionAttributeName {
            get {
                return ResourceManager.GetString("ImageSkuImageFileExtensionAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Original FileName.
        /// </summary>
        public static string ImageSkuImageOriginalFileNameAttributeName {
            get {
                return ResourceManager.GetString("ImageSkuImageOriginalFileNameAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Original FileUri.
        /// </summary>
        public static string ImageSkuImageOriginalFileUriAttributeName {
            get {
                return ResourceManager.GetString("ImageSkuImageOriginalFileUriAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LovId.
        /// </summary>
        public static string LovIdAttributeName {
            get {
                return ResourceManager.GetString("LovIdAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New Attribute&gt;.
        /// </summary>
        public static string NewAttributeName {
            get {
                return ResourceManager.GetString("NewAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Enrichment Copy.
        /// </summary>
        public static string SchemaEnrichmentCopyAttributeName {
            get {
                return ResourceManager.GetString("SchemaEnrichmentCopyAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Enrichment Image.
        /// </summary>
        public static string SchemaEnrichmentImageAttributeName {
            get {
                return ResourceManager.GetString("SchemaEnrichmentImageAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy Enrichment Copy.
        /// </summary>
        public static string TaxonomyEnrichmentCopyAttributeName {
            get {
                return ResourceManager.GetString("TaxonomyEnrichmentCopyAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy Enrichment Image.
        /// </summary>
        public static string TaxonomyEnrichmentImageAttributeName {
            get {
                return ResourceManager.GetString("TaxonomyEnrichmentImageAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxonomyId.
        /// </summary>
        public static string TaxonomyIdAttributeName {
            get {
                return ResourceManager.GetString("TaxonomyIdAttributeName", resourceCulture);
            }
        }
    }
}
